### PR TITLE
fix: clone headers in all constructors

### LINKED ISSUE #5: Fix how headers are used in Request and Response
Currently the Request and Response classes will use the headers instance passed to their constructor. This is invalid and they should both iterate over a passed in headers instance and create a new headers instance based on the previous one.

I don't want to muddy the spec API so I think we should add a util method that clones a Header instance.

This is a required change before initial release

### PR DESCRIPTION
**Pull request by calebboyd**
Excited to use this - This PR should close #5 !

Since header objects are iterable records they should be able to clone themselves
 
- I added a symbol check to short circuit init/validation and deeply copy the internal map
- fixed up the iterator type and implementation
- fixed some tests for boxed primitives and added a few for the else branches and reference equality checks.

The Request/Response constructors can now just use `new Headers`

### CODE REVIEW

File: src/headers.js [hunk 1]
```diff
@@ -27,12 +31,9 @@ class Headers {
...
     const [normalizedHeaderName, normalizedHeaderValue] = normalizeAndValidateHeaderArguments(name, value)
 
-    const existingHeaderValue = Map.prototype.get.call(this[kHeaders], normalizedHeaderName)
-    if (existingHeaderValue) {
-      Map.prototype.set.call(this[kHeaders], normalizedHeaderName, existingHeaderValue.concat([normalizedHeaderValue]))
-    } else {
-      Map.prototype.set.call(this[kHeaders], normalizedHeaderName, [normalizedHeaderValue])
-    }
+    const existingHeaderValue = (Map.prototype.get.call(this[kHeaders], normalizedHeaderName) || []).slice()
+    existingHeaderValue.push(normalizedHeaderValue)
```
Comment (calebboyd) [inline src/headers.js:35]: This approach over 3 runs before/after yielded about 3 percent perf bonus in the comparative benchmark

.concat |  
-- | --
70.762 | 70.751
70.515 | 70.548
70.614 | 70.59
70.63033333 | 70.62966667
  |  
.push |  
74.343 | 74.382
71.04 | 71.015
74.437 | 74.438
73.27333333 | 73.27833333

File: src/headers.js [hunk 2]
```diff
@@ -10,13 +10,17 @@ class Headers {
...
+    if (init && typeof init === 'object') {
       if (Array.isArray(init)) {
         for (let i = 0, header = init[0]; i < init.length; i++, header = init[i]) {
           if (header.length !== 2) throw TypeError('header entry must be of length two')
           this.append(header[0], header[1])
         }
-      } else if (typeof init === 'object' && !types.isBoxedPrimitive(init)) {
+      } else if (kHeaders in init) {
+        for (const [name, values] of init[kHeaders]) {
+          this[kHeaders].set(name, values.slice())
```
Comment (calebboyd) [inline src/headers.js:21]: I wasn't sure here if I should follow the pattern of using prototype methods. Is there any specific reason that is done here?

File: src/headers.js (hunk 1 above)
Comment (calebboyd) [reply src/headers.js:35]: Probably a fluke since the benchmarks don't use this code 😂

**Comment by Ethan-Arrowood** [comment]
This looks really good except I don't think the cloning should happen within the constructor. By spec, the Headers class does not take an instance of itself. 

I think you should make a function inside of util.js that if the argument is a headers instance, it will return a new instance filled with the entries from the previous one.

Furthermore, since I'm looking at the spec again apparently the `Symbol.iterator` should return `Iterable<string, string>` not `Iterable<string, string[]>`. Are you interested in making that change in this PR too?

**Comment by mcollina** [comment]
I'm also wondering if this might cause some perf issues.

**Comment by Ethan-Arrowood** [comment]
> I'm also wondering if this might cause some perf issues.

We can surely get creative with how we clone things. The header class uses a map underneath the hood so we really only need to clone that piece (and skip all of the revalidation). Maybe the util method can create a new Header class instance and then hardwire a clone of the Map rather than iterating and re-appending everything.

**Comment by calebboyd** [comment]
>the Headers class does not take an instance of itself.

The Headers class is a `record<ByteString, ByteString>` which is accepted by the spec as a constructor argument

> Furthermore, since I'm looking at the spec again apparently the Symbol.iterator should return Iterable<string, string> not Iterable<string, string[]>. Are you interested in making that change in this PR too?

So this one should probably be a separate PR to satisfy iterable, we also need to add

`.entries`
`.values`

The signature change I made is valid still - eg the iterator is the thing returned by the iterable's iterator symbol

>I'm also wondering if this might cause some perf issues.

For cloning performance -- We could just get rid of the string[] values and use a string -- I'm currently skipping the revalidation but have to explicitly iterate to copy that array. If it were a a map of primitives we could just `new Map(this[kHeaders])`

**Comment by Ethan-Arrowood** [comment]
> The Headers class is a `record<ByteString, ByteString>` which is accepted by the spec as a constructor argument

Ahh yes good point. I'm okay with this then!

> So this one should probably be a separate PR to satisfy iterable, we also need to add

I'll open a new issue now :+1:

> The signature change I made is valid still

yep! good change there too

> For cloning performance -- We could just get rid of the string[] values and use a string -- I'm currently skipping the revalidation but have to explicitly iterate to copy that array. If it were a a map of primitives we could just `new Map(this[kHeaders])`

Now that i think about it, there is not reason to store headers as an array... its not like you can selectively delete by value or anything. Okay, so similarly, are you willing to make that change in this PR? I understand not gold-plating with the iterable changes but i think these header changes will be great for spec compliance and performance :smile:

**Comment by calebboyd** [comment]
Changes in and tests updated! Gold plating included ;)

**Comment by Ethan-Arrowood** [comment]
This looks great! Can you update the README docs?

**Review by Ethan-Arrowood — CHANGES_REQUESTED** [review]
Looks great; one last change.

Apologies, but I think we should remove the `entries`, `keys`, and `values` methods. I dug into it a bit more and something that _implements iterable_ only has to implement the `[Symbol.iterator]` method. Those other methods are not apart of that as far as I can tell. 

All in all: remove those three methods and the corresponding tests and then I believe we are good to go. Thank you again for working through this with us!

File: README.md [hunk 3]
```diff
@@ -153,18 +156,20 @@ Represents a WHATWG Fetch Spec [Headers Class](https://fetch.spec.whatwg.org/#he
...
 ### `new Headers([init])`
 
-* **init** `[string, string][] | Record<string, string>` (optional) - Initial header list to be cloned into the new instance
+* **init** `Iterable<[string, string]> | Record<string, string>` (optional) - Initial header list to be cloned into the new instance
 
 ```js
 new Headers()
 
-new Headers([
+const headers = new Headers([
```
[the remark this answers is not in the document]
Comment (calebboyd) [reply README.md:164]: I'm using this variable in the subsequent init example -- Would you still like this change?

[the remark this answers is not in the document]
Comment (Ethan-Arrowood) [reply README.md:164]: Oh! Missed that. Can you put them next to each other then?

**Comment by calebboyd** [comment]
>Apologies, but I think we should remove the entries, keys, and values methods. I dug into it a bit more and something that implements iterable only has to implement the [Symbol.iterator] method.

Hey No worries... If you reference [this](https://heycam.github.io/webidl/#idl-iterable), an IDL specified `iterable` interface in ecmascript implies those methods. It actually looks like I forgot `.forEach`

`Note: In the ECMAScript language binding, an interface that is iterable will have entries, forEach, keys, values, and @@iterator properties on its interface prototype object.`

**Comment by Ethan-Arrowood** [comment]
> Hey No worries... If you reference [this](https://heycam.github.io/webidl/#idl-iterable), an IDL specified `iterable` interface in ecmascript implies those methods. It actually looks like I forgot `.forEach`
> 
> `Note: In the ECMAScript language binding, an interface that is iterable will have entries, forEach, keys, values, and @@iterator properties on its interface prototype object.`

Okay cool I'm good with this then, and if we are still wrong then we can always change it later.

Add forEach and then lets get this merged. Thanks again for your work on this!

**Comment by calebboyd** [comment]
Already snuck it in ;)

File: README.md [hunk 4]
```diff
@@ -264,27 +270,97 @@ headers.set('foobar', 'buzz')
...
+
+for (const name of headers.keys()) {
+	console.log(name)
+}
+
+// -> 'abc'
+// -> 'def'
+// -> 'ghi'
+```
+#### `Headers.forEach(callback, [thisArg])`
```
Comment (Ethan-Arrowood) [inline README.md:318]:
```suggestion
#### `Headers.forEach(callback, [thisArg])`

- callback `(value: string, key: string, iterable: Headers) => void`
- thisArg `any` (optional)
```

File: README.md [hunk 5]
```diff
@@ -264,27 +270,97 @@ headers.set('foobar', 'buzz')
...
+
+Returns: `void`
+
+A Headers class can be iterated using `.forEach(callback, [thisArg])` where the callback has the following signature
+
+`(value: string, key: string, iterable: Headers) => void`
```
Comment (Ethan-Arrowood) [inline README.md:324]: move to top of documentation block

```suggestion

```

File: README.md [hunk 6]
```diff
@@ -264,27 +270,97 @@ headers.set('foobar', 'buzz')
...
+
+// -> 'abc'
+// -> 'def'
+// -> 'ghi'
+```
+#### `Headers.forEach(callback, [thisArg])`
+
+Returns: `void`
+
+A Headers class can be iterated using `.forEach(callback, [thisArg])` where the callback has the following signature
```
Comment (Ethan-Arrowood) [inline README.md:322]:
```suggestion
A Headers class can be iterated using `.forEach(callback, [thisArg])`
```

**Review by Ethan-Arrowood — APPROVED** [review]
Just some quick documentation adjustments and this is good to go 🚀

File: README.md (hunk 4 above)
Comment (calebboyd) [reply README.md:318]: Gotcha, should've looked at the other parameterized methods - kept * style as with the others.

**Review by Ethan-Arrowood — APPROVED** [review]
LGTM 🚀
